### ISSUE TITLE
BRACE YOURSELF not working

### ISSUE THREAD

**Issue by cruzecontrol** [EarlyEgg/hubot-memecaptain#2]
This meme was not working.  I replaced it with the following.  I don't know why it failed before, but it now works, and you can use 'yourself' or (more in line with the original quote) 'yourselves.'

  robot.respond /brace (yourself|yourselves) (.+)/i, (msg) ->
    generateMeme(msg, '_I74XA', "Brace #{msg.match[1]}", msg.match[2])

**Comment by EarlyEgg** [comment]
Thank, I took this and replaced it in the script.
Brace yourself was working for me, but your regex is an enhancement anyway.
