### ISSUE TITLE
memes still respond with a 404 error

### ISSUE THREAD

**Issue by damacus** [EarlyEgg/hubot-memecaptain#3]
with the updated plugin I'm still getting a 404 error

**Comment by EarlyEgg** [comment]
for all memes? Or just a specific one? 
On what kind of server / internet connection do you run your hubot? Maybe you have to tweak the tries and the timer settings to get it work correctly.

**Comment by EarlyEgg** [comment]
Does this issue still exist or was it fixed by tweaking the settings?

**Comment by damacus** [comment]
Oh I think it's fixed now.
Looked like a mix up or interaction with existing plugins.

Can close this now thanks!
